# Generated by Django 5.1.1 on 2025-05-15 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0001_initial'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissionais',
            name='especialidade',
            field=models.ManyToManyField(related_name='profissionais', to='servicos.servicos'),
        ),
    ]
