# Generated by Django 5.1.1 on 2025-05-15 04:07

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0002_profissionais_especialidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissionais',
            name='dias_trabalho',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Segunda', 'Segunda'), ('Terça', 'Terça'), ('Quarta', 'Quarta'), ('Quinta', 'Quinta'), ('Sexta', 'Sexta'), ('Sabado', 'Sabado'), ('Domingo', 'Domingo')], default='', max_length=100),
        ),
    ]
