# Generated by Django 5.1.1 on 2025-05-15 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0003_profissionais_dias_trabalho'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiasTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('Segunda', 'Segunda'), ('Terça', 'Terça'), ('Quarta', 'Quarta'), ('Quinta', 'Quinta'), ('Sexta', 'Sexta'), ('Sabado', 'Sabado'), ('Domingo', 'Domingo')], max_length=10, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profissionais',
            name='dias_trabalho',
        ),
        migrations.AddField(
            model_name='profissionais',
            name='dias_trabalho',
            field=models.ManyToManyField(related_name='profissionais', to='profissionais.diastrabalho'),
        ),
    ]
