# Generated by Django 5.1.1 on 2025-05-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0004_diastrabalho_remove_profissionais_dias_trabalho_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissionais',
            name='hora_final_trabalho',
            field=models.TimeField(default='18:00'),
        ),
        migrations.AddField(
            model_name='profissionais',
            name='hora_inicio_trabalho',
            field=models.TimeField(default='08:00'),
        ),
    ]
