# Generated by Django 5.1.1 on 2025-05-16 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('profissionais', '0005_profissionais_hora_final_trabalho_and_more'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_agendamento', models.DateTimeField()),
                ('nome_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='clientes.clientes')),
                ('nome_profissionais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='profissionais.profissionais')),
                ('nome_servico', models.ManyToManyField(related_name='agendamentos', to='servicos.servicos')),
            ],
        ),
    ]
