# Generated by Django 5.1.1 on 2025-05-16 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_rename_nome_cliente_agendamentos_nome_cliente_agendamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamentos',
            old_name='nome_cliente_agendamento',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='agendamentos',
            old_name='nome_profissionais',
            new_name='profissional',
        ),
        migrations.RenameField(
            model_name='agendamentos',
            old_name='nome_servico',
            new_name='servicos',
        ),
    ]
