# Generated by Django 5.1.1 on 2025-05-16 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='data_nascientp',
            new_name='data_nasciento',
        ),
    ]
