# Generated by Django 5.1.1 on 2025-05-16 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_rename_data_nascientp_clientes_data_nasciento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='data_nasciento',
            new_name='data_nascimento',
        ),
    ]
